### ISSUE TITLE
1.21 Weapon Bug

### ISSUE THREAD

**Issue by makumaku1974** [ThexXTURBOXx/balkons-weaponmod#36] opened 2024-06-27 07:20 UTC

**Comment by ThexXTURBOXx** [comment] 2024-06-27 07:50
Could you maybe describe the bug?

**Comment by makumaku1974** [comment] 2024-06-27 10:19
List: Musket, Pistol, Blunderbuss, Hand Mortar, Crossbow can block Skeleton attacks when reloading.

**Comment by ThexXTURBOXx** [comment] 2024-06-27 13:19
Okay, thanks! I will close this as a duplicate of #32 then

**Closed as completed by ThexXTURBOXx** 2024-06-27 13:19 UTC
Labels: bug, duplicate
