### ISSUE TITLE
[fabric 1.19.4] lag problem

### ISSUE THREAD

**Issue by koksu2005** [ThexXTURBOXx/balkons-weaponmod#69] opened 2024-08-29 17:05 UTC
Whenever i throw a spear or a dagger or a shoot a musket i have a high ping spike even in singleplayer somehow

**Comment by koksu2005** [comment] 2024-08-29 17:07
and yes i tried other version and it has this problem only on version 1.19.4

**Comment by ThexXTURBOXx** [comment] 2024-08-29 17:12
I will try to investigate in around 3-4 days

**Comment by koksu2005** [comment] 2024-08-29 17:14
okay thanks

**Comment by koksu2005** [comment] 2024-08-29 17:28
i forgot to put that it only happens on big custom maps that weighs 600 mb above

**Comment by ThexXTURBOXx** [comment] 2024-09-04 10:21
Tried on a 2 GB large map (Oshode City), cannot reproduce. I think you might have other mods installed that could interfere (mixin) into BWM: Legacy's behaviour

**Comment by ThexXTURBOXx** [comment] 2024-09-04 10:29
Just tried in a rather large modpack, also does not cause lag. I will close this as unreproducible.

**Closed as not planned by ThexXTURBOXx** 2024-09-04 10:29 UTC
Labels: bug
