### ISSUE TITLE
Game crashes whenever I Access Inventory

### ISSUE THREAD

**Issue by J1Angler** [ThexXTURBOXx/balkons-weaponmod#72] opened 2024-09-16 02:15 UTC
Title says it all. The game crashes when I click on the combat tab or use the searchbar in Inventory. The problem persists even when I disable all other mods. The "cloth_config" and "architectury" associate mods are the most recent. I'm using the most recent version of 1.21.1 with NeoForge. Attached is my crashlog.
[crash-2024-09-15_19.11.40-client.txt](https://github.com/user-attachments/files/17008171/crash-2024-09-15_19.11.40-client.txt)

**Comment by ThexXTURBOXx** [comment] 2024-09-16 04:16
Duplicate of #71

**Closed as completed by ThexXTURBOXx** 2024-09-16 04:17 UTC
Labels: bug, duplicate

**Comment by J1Angler** [comment] 2024-09-30 19:04
Can you provide me with the edited API?  I can't make the edit.
