### ISSUE TITLE
Game Crashes, Minecraft 1.21.1, Neoforge, mod version 1.22.2

### ISSUE THREAD

**Issue by ZcanKal** [ThexXTURBOXx/balkons-weaponmod#74] opened 2024-10-05 05:17 UTC
The game crashes, strangely, whenever I open the inventory.  Here's my latest crash log, and game log:
[crash-2024-10-04_21.47.25-client.txt](https://github.com/user-attachments/files/17265223/crash-2024-10-04_21.47.25-client.txt)
[latest.log](https://github.com/user-attachments/files/17265224/latest.log)
It only seems to crash once I put in BWM:L.

**Comment by ThexXTURBOXx** [comment] 2024-10-05 06:10
Duplicate of #71

**Closed as completed by ThexXTURBOXx** 2024-10-05 06:10 UTC
Labels: bug, duplicate
